### ISSUE TITLE
The [add statement] link should be more prominent

### ISSUE THREAD

**Issue by CatalinFrancu** [TeamDignitas/dignitas#130]
Should be on the home page.

Also, when adding a statement, there should be a link [add new author] under the author field.

**Comment by sandriu** [comment]
First part is done:
![Screenshot_2020-07-06_12-13-03](https://user-images.githubusercontent.com/1265882/86577065-58853500-bf82-11ea-99f6-e39217ed9f2a.png)

**Comment by sandriu** [comment]
Warning! The label for "Contribuie și tu" (see above screenshot) is hardcoded, it needs to be translated automatically @CatalinFrancu .

**Comment by CatalinFrancu** [comment]
c1547da6912234e62a69ba26eb8f24d13beb108d adds a "add author link" under the author field.
