### ISSUE TITLE
Help page history should be hidden if empty

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#154]
See below screenshot from mobile.
Instead of an empty table, a message like 'Nu există istoric' should be displayed. Or deactivate the link for this page if the page is empty.

![bug-missing-empty-state](https://user-images.githubusercontent.com/1265882/93068804-9e96fd00-f685-11ea-8a4d-d0b63b8030ca.jpg)

**Comment by CatalinFrancu** [comment]
I added a message when the history is empty: 

> There are no changes to this item. The current version is the only version.

About hiding the button altogether: The reason why the history is sometimes empty is that the user can click [Save] without changing anything. This creates a revision that's identical to the previous one. We can check for this and skip the database changes, but it would complicate the code (basically every edit page would need to check all the object's fields). I would postpone this until it becomes a problem in practice.
