### ISSUE TITLE
Check writing style for UI elements and Help pages

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#157]
Recommended writing style: [Google Material Design Writing principles](https://material.io/design/communication/writing.html#principles).

Check the following UI elements or pages:
- [x] button labels, tooltips for buttons and clickable icons
- [x] alerts
- [x] dialog windows
- [x] help pages
- [x] static resources

Also check:
- [x] correct implementation of the [suggestions made](https://github.com/TeamDignitas/dignitas/issues/157#issuecomment-728080426);
- [ ] items marked as not implemented.

**Comment by sandriu** [comment]
@CatalinFrancu Help pages checked, see attached PDF for proposed changes.
[Stilul de scris pentru componente UI - Paginile de Ajutor.pdf](https://github.com/TeamDignitas/dignitas/files/5317774/Stilul.de.scris.pentru.componente.UI.-.Paginile.de.Ajutor.pdf)

**Comment by sandriu** [comment]
The final document is here. We need to discuss it page by page @CatalinFrancu .
[Stilul de scris pentru componentele UI cf. Google Design.pdf](https://github.com/TeamDignitas/dignitas/files/5546751/Stilul.de.scris.pentru.componentele.UI.cf.Google.Design.pdf)

**Comment by sandriu** [comment]
The updated document is here. I verified which suggestions were implemented and which not. There are a few more things to fix, see cells marked with yellow background.
[Stilul de scris pentru componentele UI cf. Google Design (revizuit 15feb2021).pdf](https://github.com/TeamDignitas/dignitas/files/5995586/Stilul.de.scris.pentru.componentele.UI.cf.Google.Design.revizuit.15feb2021.pdf)

**Comment by CatalinFrancu** [comment]
TODOS after the second pass:

* [ ] Show a snackbar when a moderator accepts/unaccepts an answer.
* [ ] Brainstorm about undoing a review vote. This will be inherently impossible if the vote was the last necessary vote (or if the user is a moderator and therefore can settle reviews unilaterally).
* [ ] Change verb to singular on date picker modal.
* [ ] Change verb to singular on review button confirmation.

Other notes:

* I stand corrected, users do need 100 rep to upload attachments. This may be unreasonable and we may lower it, but there should be a limit (even 10).
* #224 (snackbars) is underway.
* #226 (shorten button name on flag modal) should be done.

**Comment by sandriu** [comment]
> * [ ]  Brainstorm about undoing a review vote. This will be inherently impossible if the vote was the last necessary vote (or if the user is a moderator and therefore can settle reviews unilaterally).

To avoid this impossible Undo, we agreed to add a tootip on the 'păstrează' button, in order to inform the user that this action cannot be undone. See #236 .

> * I stand corrected, users do need 100 rep to upload attachments. This may be unreasonable and we may lower it, but there should be a limit (even 10).

Ok then, we will lower the limit in the future, as needed.

**Comment by sandriu** [comment]
I re-checked the remaining issues, everything is fixed now (except for #236, which is WIP). We can close this ticket.
