### ISSUE TITLE
Images scale unequally in statement list

### ISSUE THREAD

**Issue by CatalinFrancu** [TeamDignitas/dignitas#164]
The relevant code is in `templates/bits/statement.tpl`, which includes `templates/bits/image.tpl`.

![Screenshot_2020-09-24_17-50-17](https://user-images.githubusercontent.com/1180392/94161574-7f228000-fe8e-11ea-84cb-c2bd2254d595.png)

**Comment by sandriu** [comment]
These images still have a bug, because some of them are not cropped to a perfect circle, see #168 .
