### ISSUE TITLE
Images for entities and users are not cropped to a perfect circle

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#168]
Although we used the Bootstrap 4 .rounded-circle and .img-fluid classes, these images are not cropped to a perfect circle (width = height). This bug appears on various pages, like home page, user profile etc.

> ![oval-thumbnail-user](https://user-images.githubusercontent.com/1265882/94428917-3292b980-019a-11eb-90c0-07b65572ae01.png)

> ![image-101-96px](https://user-images.githubusercontent.com/1265882/94428944-3cb4b800-019a-11eb-9d24-5d788718c67c.png)

**Comment by CatalinFrancu** [comment]
We discussed this in person. We agreed to

- [ ] have a dashboard report and/or e-mail report for images that are skewed beyond an acceptable margin;
- [ ] encourage the users to upload square-ish images, via a tooltip;
- [ ] add this recommendation to the entity help page.

We can add an image cropping tool in the future when we scale up.
