### ISSUE TITLE
Fix UI inconsistencies

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#184]
- [x] on Predefined Answers page, the edit action is marked just with an edit icon, while on other similar listing pages, the edit action is marked with a text button:

> ![edit-action-as-icon](https://user-images.githubusercontent.com/1265882/100216887-806a3a80-2f1b-11eb-9e38-c59139395f61.png)

> ![edit-action-as-text-button](https://user-images.githubusercontent.com/1265882/100216902-83fdc180-2f1b-11eb-912f-83daf6f76535.png)

All listing pages should display the edit action in the same way.

**Comment by sandriu** [comment]
All listing pages look the same now.

@CatalinFrancu There are still two pages without a "cancel" button (https://dignitas.ro/editeaza-eticheta and https://dignitas.ro/editeaza-regiune), while all other pages have a pair of cancel-save buttons. What's the reason for this difference, please?

**Comment by CatalinFrancu** [comment]
We use the same page template when editing a tag and when adding a new tag (and likewise for regions). We had a cancel link when editing tags, but not when adding one. Fixed now!
