### ISSUE TITLE
Hide extra actions for a statement/answer/entity under an ellipsis menu

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#187]
On a statement page, there are many secondary actions, for both statement context/scope and answers (permalink, edit, etc):

> ![many-actions-statement](https://user-images.githubusercontent.com/1265882/100254419-f6d26100-2f4a-11eb-986d-c32472d02312.png)

> ![many-actions-answer](https://user-images.githubusercontent.com/1265882/100254427-fa65e800-2f4a-11eb-9ea2-d8ba6f5b3980.png)

There should be only 1-2 secondary actions visible and the others moved to an ellipsis menu with dropdown, similar to this [upper menu example](https://lh3.googleusercontent.com/TzUu6hL-TAmNqupMsuXtwsjzTSPkLRrUhL02Xluo3-HdhRzQZSIkfVbQZAEcyvjxloAx_D1ufZnq_GCHTRUvsZrEyUW9FLBsiJ8yeA=w1064-v0).

**Comment by sandriu** [comment]
Ellipsis icon is here https://fontawesome.com/icons/ellipsis-v?style=solid

**Comment by CatalinFrancu** [comment]
Added text. TODO: determine if we should keep the 0.75rem font size on the dropdown (set in `main.css:.answer-footer *`)

**Comment by sandriu** [comment]
> determine if we should keep the 0.75rem font size on the dropdown

The answer is yes, because the ellipsis menu represents secondary actions with low priority:

> ![ellipsis-menu](https://user-images.githubusercontent.com/1265882/100872863-22a19980-34ab-11eb-9fa6-5ba53d8ff280.png)

**Comment by sandriu** [comment]
> Also, the blue border around the ellipsis (when clicked) is kind of ugly. Should we hide it?

@CatalinFrancu The blue border is the default focus state for any Bootstrap button, see another example:

> ![Screenshot_2020-12-02_15-21-09](https://user-images.githubusercontent.com/1265882/100878019-4ae0c680-34b2-11eb-8beb-cc6228433dda.png)

**Comment by sandriu** [comment]
@CatalinFrancu a similar ellipsis menu must be added for statement actions (only the comment icon to be left outside ellipsis menu) and for the comment actions (comment within an answer).

**Comment by CatalinFrancu** [comment]
Closing (I think it's done).
