### ISSUE TITLE
Add truth scale and other informations on project's description page

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#194]
This page https://dignitas.ro/despre describes the overall project and it should also mention:
1) the truth scale we use;
2) how to contribute to this project;
3) the fact that Dignitas is a non-partisan organisation (eg. founding members are not members of any political party and the platform is not endorsed/financed by any political party).
Just a short paragraph for each subject, with links to Help pages for more details.

These extra informations are required if we want to list Dignitas on this global map of fact checking websites https://reporterslab.org/how-we-identify-fact-checkers/.

**Comment by sandriu** [comment]
I would only change 2 things:
- 'afirmații deja existente _în sistem_' with 'afirmații deja existente _pe site_';
- 'L-am _făcut_ în timpul nostru liber' with 'L-am _dezvoltat_ în timpul nostru liber'.

The rest is perfect.

> The [verdicts help page](https://dignitas.ro/ajutor/verdicte) discusses the distinction between _false_ and _undecidable_ statements [..] Would you like this on the About page as well?


No, there's no need, because the website content is in Romanian only.

**Comment by CatalinFrancu** [comment]
> I would only change 2 things:
> 
> * 'afirmații deja existente _în sistem_' with 'afirmații deja existente _pe site_';
> * 'L-am _făcut_ în timpul nostru liber' with 'L-am _dezvoltat_ în timpul nostru liber'.

Done.
