### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by CatalinFrancu** [TeamDignitas/dignitas#200]
Because one can never have enough glitter! See for example Duck Duck Go, which obeys the browser's dark mode setting.

See [prefers-color-scheme](https://disjfa.github.io/bootstrap-tricks/prefers-color-scheme/).

**Comment by CatalinFrancu** [comment]
We decided to put this on hold until Bootstrap adds support for this ([likely in v6](https://github.com/twbs/bootstrap/issues/27514#issuecomment-489437015)).

Without it we cannot, for example, do this:

```scss
:root {
  --link-color: blue;
}

@media (prefers-color-scheme: dark) {
  :root {
    --link-color: red;
  }
}

$link-color: var(--link-color);
```

because then `$link-hover-color` tries to call a function on a not-yet-defined color:

```
Error: argument `$color` of `darken($color, $amount)` must be a color
        on line 178:43 of www/scss/third-party/bootstrap/_variables.scss, in function `darken`
        from line 178:43 of www/scss/third-party/bootstrap/_variables.scss
        from line 9:9 of www/scss/third-party/bootstrap/bootstrap.scss
        from line 53:9 of www/scss/main.scss
>> $link-hover-color:                        darken($link-color, 15%) !default;
```

**Comment by sandriu** [comment]
Here's a list of colours and their assignment per components, in light theme and dark theme (WIP):

**Light theme:**
- primary colour: #0d6efd (blue, Bootstrap primary button)
- primary colour variant (?): #232429 (earthy black) - not linked to blue
- secondary colour: #F2CB07 (yellow)
- secondary colour variant: ...
- background colour: #FFFFFF (white)
- surface colour: #FFFFFF (white)
- error colour text: #dc3545 (red, Bootstrap danger button)
- on primary colour: #495057 (dark grey) on white;
- on secondary colour: 

Bark theme:
- primary colour:
- primary colour variant:
- secondary colour:
- secondary colour variant:
- surface colour:

**Comment by CatalinFrancu** [comment]
In case it helps, here are all the existing uses of Bootstrap's [theme colors](https://getbootstrap.com/docs/5.1/customize/color/).

### `success`, `info`, `light`, `dark`: unused

We don't use these. I actually removed them from the Bootstrap CSS.

### `butter` (our custom color)

* home page (e.g. "Contribute" header)
* navbar (including its dropdowns)

### `primary`

* many buttons and outline buttons

### `secondary`

* many buttons and outline buttons
* statement region badge
* answer verdict badge
* user reputation badge on navbar
* deleted answers and comments

### `danger`

* many outline buttons
* feedback for invalid form data
  * this includes some icons on the nav pills on the help page / help category edit pages
* deleted statements and entities
* review resolution: delete (e.g. when viewing a deleted object's version history)
* notification and review icons on the navbar
* remaining chars on fields with size limit (this shouldn't happen with normal use)

### `warning`

* closed (e.g. as duplicates) statements and answers
* editing statements, answers and entities when you can only suggest edits (you can test it with a reputation of 1,000)
* viewing statements and entities with pending edits
* review page, e.g. when the object is a duplicate
* draft indicator
* fake login button (in development only)
* date picker clear button

**Comment by sandriu** [comment]
I changed 3 colours in the Dark theme and 1 colour in the Light theme, see below PDFs:

[Comparison between Light and dark theme - v2.pdf](https://github.com/TeamDignitas/dignitas/files/7513164/Comparison.between.Light.and.dark.theme.-.v2.pdf)
[Dignitas - Light & Dark theme v2.pdf](https://github.com/TeamDignitas/dignitas/files/7513165/Dignitas.-.Light.Dark.theme.v2.pdf)
