### ISSUE TITLE
Fix these new UI bugs

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#202]
The following bugs appeared after @CatalinFrancu made some changes using SCSS.

- [x] 1) on home page, username background (top right corner) is turquoise, it should be #232429 instead:
![home_bug_username_background_is_turquoise](https://user-images.githubusercontent.com/1265882/105147060-50997680-5b09-11eb-8d8f-bb40d005c7bc.png)

- [x] 2) Informations menu (top bar) has no longer a lighter background colour. Idem for user menu:
![home_bug_username_submenu_not_lighter](https://user-images.githubusercontent.com/1265882/105147567-0b297900-5b0a-11eb-89b7-07cc15c0764b.png)

- [x] 3) Edit relation page is not styled (logging required):
![bug_dignitas_pagina_nestilata](https://user-images.githubusercontent.com/1265882/105476886-d522fb00-5ca9-11eb-8624-e940dfb4123d.png)

- [x] 4) on Edit statement page, the bottom buttons (delete, cancel, save) are not aligned anymore because there's a `div` containing the first 2 buttons. Same for Edit entity page:

![bug-edit-statement-bottom-buttons-not-aligned-anymore](https://user-images.githubusercontent.com/1265882/106010163-d1381400-60c1-11eb-9831-0de07eac5572.png)

**Comment by CatalinFrancu** [comment]
(1) is the visual indicator that the user has unread notifications. It can probably be done better, :-) but we also have the reputation number and the two should coexist somehow.

**Comment by sandriu** [comment]
For (1) the first step to declutter the top right header corner is to get rid of the language menu arrow. I've seen examples (both websites and apps) where the language menu, if displayed only as an icon (no text), doesn't have an arrow to inform users that it opens a language menu (because the globe is self-explanatory):
![massimoDuttiApp-globe-icon](https://user-images.githubusercontent.com/1265882/106276606-8264b880-6240-11eb-95fe-433f57d63bff.jpg)
