### ISSUE TITLE
User credibility rating

### ISSUE THREAD

**Issue by CatalinFrancu** [TeamDignitas/dignitas#203]
We need a metric to measure the agreement/disagreement between a user's answers' verdicts and the respective statements' verdicts. There should be some leeway, for example FALSE and MOSTLY_FALSE should not be considered a disagreement.

**Comment by CatalinFrancu** [comment]
Sounds good to me!

**Comment by sandriu** [comment]
Here's an UI proposal for user credibility rating (Bootstrap badge, just like the moderator label):
![proposal-user-credibility-rating](https://user-images.githubusercontent.com/1265882/120467663-12f70500-c3a9-11eb-9764-1f064f137520.png)

The badge could have various background colours, depending on how much the user's answers' verdicts and the respective statements' verdicts correspond (eg. green for more than 75%, yellow for 50-74%, red for 0-49%).
