### ISSUE TITLE
Summary and Scope text fields (Add affirmation page) should be text areas

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#204]
After I added several affirmations on dignitas.ro, I can tell for sure that Summary and Scope text fields should be text areas, in order to see the whole text before I save that affirmation. Just one line of text (with horizontal scrolling for reading the whole affirmation) is not enough, especially if you work on a cropped version of a political affirmation.

Text areas, if introduced, should have a limited number of characters, though.

**Comment by CatalinFrancu** [comment]
I added a limit of 500 chars (for comparison, our longest summary field has [206 chars](https://dignitas.ro/afirmatie/3)).

I switched to 3-row textareas. The user can drag to resize them if needed. I looked into resizing them dynamically using Javascript, but all the approaches were hacky.
