### ISSUE TITLE
Replace thumbs up/thumbs down icons with a geometric version

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#208]
[Material Design System Icons](https://material.io/design/iconography/system-icons.html#design-principles) uses geometric, consistent shapes and discourages the use of gestural or loose organic shapes, like the ones we have on statement pages:
![thumbs-up-down-are-loose-icons](https://user-images.githubusercontent.com/1265882/106264707-ac14e400-622e-11eb-99b0-e43cbed30993.png)
![material-design-system-icons-do-dont](https://user-images.githubusercontent.com/1265882/106265357-9522c180-622f-11eb-9dd9-129d2e5b2b8a.png)

We need to change the thumbs up/down icons with geometric versions.
Also, all other icons used on Dignitas should be checked for consistency with the new geometric style.

**Comment by sandriu** [comment]
Below is the inventory of all icons used on Dignitas (via Fontello) and the equivalent versions from Google Design Icons. All icons on Dignitas should be changed with their Google Design Icons counterparts.

Some icons from Google Design are marked with the comment "nu sunt foarte mulțumită de iconița asta" (not very content with this icon), but for now we'll stick with the chosen version.

[Inventarul iconițelor folosite pe Dignitas și echivalentul din Google Design Icons.pdf](https://github.com/TeamDignitas/dignitas/files/5981326/Inventarul.iconi.elor.folosite.pe.Dignitas.i.echivalentul.din.Google.Design.Icons.pdf)

**Comment by CatalinFrancu** [comment]
TODO @sandriu 

- [ ] On the answer resources side sheet, the expand/collapse icons are too small. Those are displayed from `main.css`, see `.card-collapse-icon .card-header a:before`.

**Comment by sandriu** [comment]
@CatalinFrancu I found drag indicators on the following pages: Edit entity, Help categories, Add statement, Canned responses and Relations types. Are there any other pages that use this kind of icon?

**Comment by CatalinFrancu** [comment]
The drag_indicator glyph is used for reordering:

* [ ] [help categories](http://localhost/dignitas/www/categorii-ajutor);
* [ ] [help pages](http://localhost/dignitas/www/editeaza-categorie-ajutor/1) within a category;
* [ ] [relationship types](http://localhost/dignitas/www/tipuri-relatii);
* [ ] [canned responses](http://localhost/dignitas/www/raspunsuri-predefinite);
* [ ] entity aliases and entity relations (both on the [entity edit page](http://localhost/dignitas/www/editeaza-autor/36));
* [ ] links (same code reused in three places: [statement sources](http://localhost/dignitas/www/editeaza-afirmatie/1), [entity links](http://localhost/dignitas/www/editeaza-autor/36), [relationship sources](http://localhost/dignitas/www/editare-relatie/20)).
