### ISSUE TITLE
Some characters not properly displayed with Spartan font

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#216]
For example the brackets `[...]`:
![bug-Spartan-font-chars-not-fully-displayed](https://user-images.githubusercontent.com/1265882/107489257-1748a980-6b91-11eb-81ff-32c726ff7ce7.png)

**Comment by sandriu** [comment]
I cannot replicate this bug anymore. Will try later.

**Comment by sandriu** [comment]
Another field with this bug:
![image](https://user-images.githubusercontent.com/1265882/110103572-c05c7b80-7dae-11eb-9567-3a7c0fc671e7.png)

**Comment by sandriu** [comment]
I managed to replicate the bug on a laptop (1920x1080), but when I press Ctrl+ once in the browser, the bug disappears. Also, on mobile this bug does not exist.

**Comment by CatalinFrancu** [comment]
I see this in my browser all the time (Brave / Linux). It looks like the square brackets are taller than capital letters, so I would start there:

![crop](https://user-images.githubusercontent.com/1180392/110119512-957d2200-7dc4-11eb-9f6d-e58408629501.png)

**Comment by sandriu** [comment]
> I see this in my browser all the time (Brave / Linux). It looks like the square brackets are taller than capital letters, so I would start there

I succeeded to cancel the effect of cropped squared brackets by adding `.form-control { height: auto; min-height: 42px; }` . But this line introduces another bug for select2 dropdown lists (relations' parties), which become smaller (38px height instead of 42px):
![old-bug-solved-new-bug-introduced](https://user-images.githubusercontent.com/1265882/110139764-0f6cd580-7ddc-11eb-864b-5bb3ce99f44f.png)

**Comment by sandriu** [comment]
Bug solved.
