### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by CatalinFrancu** [TeamDignitas/dignitas#238]
The initial functionality will simply be:

- [x] Selecting text and right clicking shows a _Submit to Dignitas_ option.
- [x] Submitting takes the user to the add statement page. The summary and source values match the selected text and page URL.
- [x] The user can fill in the blanks and create the statement.

Later improvements:

- [x] Romanian and English localization (should match the browser locale).
- [x] Configurable destination URL so other installations can use the same extension.
- [x] Detect author based on source page (should work for Facebook posts).
- [x] Persistent choice for the destination URL (currently resets on browser restart).

Post-launch

- [ ] Link and documentation (brainstorm with @sandriu)

**Comment by CatalinFrancu** [comment]
The extension now works and has its own [help page](https://dignitas.ro/ajutor/extensie-chrome).

Should we also advertise it on the add statement page?

**Comment by sandriu** [comment]
I tried to install the extension using the link from this page https://dignitas.ro/ajutor/extensie-chrome and I get the following message:
![Access-forbidden-](https://user-images.githubusercontent.com/1265882/110099154-a7050080-7da9-11eb-989f-7473c6a5d177.png)

**Comment by CatalinFrancu** [comment]
Oops! I fixed the permissions, please try again.

**Comment by CatalinFrancu** [comment]
We will reevaluate at a later time if it is worth uploading this to the Google Web Store.
