### ISSUE TITLE
Bug on Add statement page: number of characters not updated on summary field

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#244]
I used the Chrome extension to add the following statement, which needed to be shortened because it exceeded 500 characters:

> Planul Național de Relansare și Reziliență - șansa României la modernizare și reformă
> Astăzi este un moment istoric pentru România. Avem nevoie de un restart ca țară, ca națiune. Acesta este cel mai favorabil moment, chiar dacă vine în circumstanțe dificile. Putem ieși mai puternici din această criză. Am prezentat astăzi planul de reforme și investiții pe care le vom propune Comisiei Europene în cadrul Planului Național de Relansare și Reziliență. 
> Dincolo de cifrele pentru domeniile prioritare pe care le propunem - 4,4 miliarde pentru educație, 3,4 pentru Sănătate, 9,5 pentru Transport, 6,8 miliarde pentru Mediu, propunem o serie de reforme care să stea la baza modernizării și reformării României

After I shortened it, the total number of characters didn't update in the field and I still saw the initial error displayed:

![bug-camp-neactualizat-cu-nr-corect-caractere](https://user-images.githubusercontent.com/1265882/111816542-a1e59c80-88e5-11eb-92ce-0c941e94e015.png)

**Comment by CatalinFrancu** [comment]
Almost done. The errors now disappear once the constraint is satisfied.

After I implement #248, we can make the presentation even nicer. It will read "please remove 100 characters" in red when you're above the limit, instead of the current "-100 characters remaining". :smile:
