### ISSUE TITLE
Bug on Entity profile page: Visible heading but no statements in the list

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#250]
![image](https://user-images.githubusercontent.com/1265882/112661644-6b68ce00-8e5f-11eb-85fc-a8b907adb74c.png)

**Comment by sandriu** [comment]
Same bug for the field "Relations", also on Entity profile page.

**Comment by CatalinFrancu** [comment]
Done. Some profiles might consist of whitespace only, which still causes the header to display. I added code to trim whitespace from now on, but if you see any entities with empty profiles, please edit + save them.
