### ISSUE TITLE
Author's truthfulness rating

### ISSUE THREAD

**Issue by CatalinFrancu** [TeamDignitas/dignitas#265]
We should have some measure of an author's truthfulness, displayed on the entity page.

TODO @sandriu

- [x] figure out a UI

This could be a red-green gauge or meter, or we could do something in connection to our name (_dignitas_ or the lack thereof).

TODO @CatalinFrancu

- [x] figure out a good metric (the arithmetic mean, or a weighted arithmetic mean);
- [x] create a page in the Help section (production), where we explain publicly how we calculate the truthfulness rating (renamed trust level).

**Comment by sandriu** [comment]
Here's an example in which the truth scale values are combined with the number of analysed statements; this way, the fact checking website avoids using an "absolute rating", since the overall truthfulness rating of a politician would depend highly on the number of analysed statements.

![scorecard-example-Politifact](https://user-images.githubusercontent.com/1265882/141444160-6d05282c-32f1-4bab-8df6-e715980bb199.png)

On Dignitas, such a "scorecard" feature could be displayed in full using a new tab near "Statements" and "Mentions" tab, or in brief under the politician's profile photo.

**Comment by CatalinFrancu** [comment]
This *could* work, although it is still possible to skew the results. Even habitual liars tell the truth often enough. If an army of trolls adds all those statements, they can whitewash the politician.

**Comment by sandriu** [comment]
The truthfulness rating should be displayed below the author's profile photo, as a gauge with only one circle, see a JS Fiddle example [here](https://jsfiddle.net/jbdz8squ/):

![gauge-JSFiddle-Code-Playground-10-04-2024_12_20_PM](https://github.com/user-attachments/assets/5355df36-a716-4fa3-a53a-71dcc0cf67ba)



The gauge arc would be highlighted depending on the general score of the politician, which is calculated based only on statements (or promises) that have a verdict.

The general score of the politician is calculated as a weighted arithmetic mean, based on this formula:
- each _true statement_ (or _Kept promise_, or _Not a flip-flop_) brings +1 point (plus one point);
- each _generally true statement_ (or _Kept, but late promise_) brings +0.5 point;
- each _mixed statement_ (or _Partially kept promise_, or _Half-flop_) brings 0 points;
- each _generally false_ (or _Blocked promise_) statement brings -0.5 point;
- each _false statement_ (or _Broken promise_, or _Flip-flop_) brings -1 point (minus one point).

**Comment by CatalinFrancu** [comment]
Implemented the above. Settings can be tweaked from:

* [view.css](https://github.com/TeamDignitas/dignitas/blob/master/www/css/autoload/entity/view.css): CSS code.
* [trustLevel.tpl](https://github.com/TeamDignitas/dignitas/blob/master/templates/bits/trustLevel.tpl): HTML code.
  * Plus a very basic `display: flex` wrapper in [entity.tpl](https://github.com/TeamDignitas/dignitas/blob/master/templates/bits/entity.tpl#L20).
* [TrustLevel.php](https://github.com/TeamDignitas/dignitas/blob/master/lib/TrustLevel.php): PHP code.

**Comment by sandriu** [comment]
We also need to create a page in the Help section, to explain publicly how we calculate the truthfulness rating (renamed trust level).

**Comment by CatalinFrancu** [comment]
Here is an attempt: https://dignitas.ro/ajutor/nivel-incredere

Let us tweak it, then once we are happy with it I can translate it into English as well.
