### ISSUE TITLE
Upgrade to Bootstrap 5

### ISSUE THREAD

**Issue by CatalinFrancu** [TeamDignitas/dignitas#275]
Post-release:

* [x] Replace `data-toggle` with `data-bs-toggle` in answerResources.html (two occurrences).
* [x] Replace `white` with `border-white` in homepage-bottom.html (both locales).
* [x] Upgrade all static resources.

**Comment by sandriu** [comment]
After I tested the new version on desktop and mobile, I have found the following UI differences or bugs. I will try to solve them:
Desktop:
- [ ] on Statement page, the answer grey area is not aligned anymore with the author card (not wide enough);
- [ ] on Add/Edit statement page, the tags don't have anymore a background colour;
- [ ] on the following tables the horizontal line between table head and first row is missing: Domains, Canned responses, Author types, Relationship types, Static resources;
- [ ] on Regions page, the Save button at the end of the page has blue background (primary action), it should be outlined with white background (secondary action);
- [ ] BUG: on Statement page, the side sheet (with Tips for answering) is not collapsable / expandable anymore;
- [ ] BUG: on Edit author page, the dropdown list for relations has text and arrow overlapped.

Mobile:
- [ ] on global navigation menu, there is no vertical space between hamburger menu (bottom margin) and page content;
- [ ] on Statement page, the answer area does not have grey area for editor buttons anymore (it's white) and left border of answer card is missing;
- [ ] on Dashboard, the card for Review queues is wider than the rest of cards;
- [ ] on search results page, cards for authors are wider than the filters and there's little horizontal space left between cards and right edge of the page.

**Comment by CatalinFrancu** [comment]
A couple of comments so far:

> * [ ]  on Add/Edit statement page, the tags don't have anymore a background colour;

This was not the case under Bootstrap 4 either. I can fiddle with the Select2 pills if this is important.

> * [ ]  BUG: on Statement page, the side sheet (with Tips for answering) is not collapsable / expandable anymore;

This will go away once we edit the corresponding [static resource](https://dignitas.ro/editeaza-resursa-statica/16) and replace `data-toggle` with `data-bs-toggle`. I did this on staging just now.
