### ISSUE TITLE
Add generic photo for a contributor's profile

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#296]
If a contributor doesn't use a profile photo on his/her profile page, then a generic photo should be used. 
Below is the case of a contributor with no profile photo, and the accuracy tag is displayed too high:
![dignitas-ss-contributor-without-photo](https://user-images.githubusercontent.com/1265882/142860022-69dcce62-a767-4e58-9332-a2aa793dfb0b.png)

**Comment by CatalinFrancu** [comment]
I used the 'person' icon from material icons. Feel free to adjust it further!

**Comment by sandriu** [comment]
As stated [here](https://github.com/TeamDignitas/dignitas/pull/307#issuecomment-1016433373), the username appears capitalised because there's this style applied `h1::first-letter { text-transform: capitalize; } ` (which makes sense if the page name translation does not take into account the capitalisation).
So we need an exception from this style.
