### ISSUE TITLE
Missing border for some buttons on homepage

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#327]
![Dignitas-ss-bug-missing-border-some-buttons-homepage](https://user-images.githubusercontent.com/1265882/187675008-f8b11646-ab83-47be-9e4d-96efed6fd629.png)

**Comment by CatalinFrancu** [comment]
Solved by replacing `btn-warning` (a color we removed from Bootstrap) with `btn-secondary`.
