### ISSUE TITLE
Statements list for a region/tag is not fully displayed

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#336]
On a page like this https://dignitas.ro/regiune/10/bucuresti , the statements list either lacks pagination or there's a bug that prevents displaying the full list. There's a similar problem with the Authors' list, on the same page:

![bug-regiune-București-Dignitas](https://github.com/TeamDignitas/dignitas/assets/1265882/69257ec2-a711-4d8e-9504-df7d6c8cf123)

**Comment by CatalinFrancu** [comment]
Done. I was only postponing it because there weren't enough statements anyway. 🙂

Keeping this issue open to do the same for a region's authors.
