### ISSUE TITLE
Bug: independent politicians cannot be marked as independent

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#344]
Case study: [Mircea Geoană](https://dignitas.ro/autor/129/mircea-geoana). I cannot complete his profile with his current relationship ('independent') because the Target field (in the Edit author page) cannot be empty for now.

**Comment by CatalinFrancu** [comment]
We managed to achieve this using the existing data structure. I documented the process on the [wiki page](https://github.com/TeamDignitas/dignitas/wiki/Moderator-guide#creating-independent-politicians).
