### ISSUE TITLE
CSS styles to be configured via LESS instead of overriding the Bootstrap CSS

### ISSUE THREAD

**Issue by sandriu** [TeamDignitas/dignitas#74]
This is a _work in progress_ list:

`body { font-family: Spartan, Helvetica, Calibri, Arial, sans-serif; }`

```
.btn-group-sm>.btn, .btn-sm { 
    border-radius: 1rem;
    padding: .5rem 0.8rem .25rem; /* required because of Spartan font */
} 
```
```
.form-control {
  padding: 1.2rem .75rem; /* instead of padding: .375rem .75rem; */
}
```
```
.navbar {
    padding: 0rem 1rem; /* instead of padding: .5rem 1rem; */
}
```

**Comment by sandriu** [comment]
Please note that some of the above styles with solve visual bugs, like the insufficient top padding for buttons when we use Spartan font.
![bug_incorrect_padding_button_with_Spartan_font](https://user-images.githubusercontent.com/1265882/82662329-536c6080-9c36-11ea-8acc-b77d55656ea4.png)

**Comment by CatalinFrancu** [comment]
There is now a new file, `www/scss/main.scss`. For a list of variables that can be customized, see `www/scss/third-party/bootstrap/_variables.scss`.

TODO (I can help with this):

- [ ] Go through `main.css` and see if any other tweaks can be rewritten as Sass.

**Comment by CatalinFrancu** [comment]
I think this is done. Feel free to reopen if you notice anything wrong!
